### ISSUE TITLE
An "Includes" Feature in a Yaml

### ISSUE THREAD

**Issue by MattHodge** [bundyfx/vamp#1]
Provides similar functionality to a composite resource, but you could do:

``` yaml
Includes
  - windows_base.yaml
  - cis_compliance.yaml
```

and these would be ported into the resource

**Comment by bundyfx** [comment]
Complete - multiple configurations can be placed into the vampspec file now under the 'configs' tag (see example vampspec.yml in root). On compile vamp will take all the yml files specified in the specfile and roll them into a single mof that corresponds to the nodenames in the specfile.
