### ISSUE TITLE
Automatic Module Installation 

### ISSUE THREAD

**Issue by MattHodge** [bundyfx/vamp#2]

**Comment by bundyfx** [comment]
Added the prep switch parameter to vamp that will go through all of the config .yml files and assess the required modules and version. Once its gathered this information it will check against what is installed locally and download from PSgallery anything that is required but not installed. The concept with this is that a copy of vamp would be on a remote node in which if you wanted to automate the process of downloading modules prior to dsc execution your 'runner' script would simply container two or three lines - ie.

vamp -prep
vamp
start-dscconfiguration .\mofs
