### ISSUE TITLE
how would you create property which requires pscredential type but is not called password and username property is not present for the resource

### ISSUE THREAD

**Issue by ivnovi** [bundyfx/vamp#21]

**Comment by flynnCoolblue** [comment]
This is sort of where I got up too before slowing down on this project. It's something that would need to be solved before it could be used as a 1:1 replacement. Always welcome for Pull Requests if you think of a creative way to handle this :)

**Comment by ivnovi** [comment]
I've been looking into ansible lately, and using credparam_username and credparam_password makes it pscredential under the hood. this is probably most straightforward approach, or just use ansible? :)

**Comment by bundyfx** [comment]
Agreed, Ansible is awesome when it comes to that sort of thing. I actually started this project before I knew much about Ansible. I would highly recommend everyone use Ansible for Windows Configuration management.
